apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-gmail
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'tphatnguyen237@gmail.com'
      smtp_auth_username: 'tphatnguyen237@gmail.com'
      smtp_auth_password: 'fushtggrlumsehih'
      smtp_require_tls: true

    route:
      receiver: 'gmail'
      group_by: ['alertname', 'type']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 3h

    receivers:
    - name: 'gmail'
      email_configs:
      - to: 'tphatnguyen237@gmail.com'
        require_tls: true
        headers:
          subject: '[{{ "{{" }} .Status | toUpper {{ "}}" }}] {{ "{{" }} .CommonLabels.alertname {{ "}}" }}'
