apiVersion: v1
kind: Service
metadata:
  name: icinga2
  namespace: monitoring
  labels:
    app: icinga2
spec:
  ports:
    - name: web
      port: 5665
      targetPort: 5665
      protocol: TCP
  selector:
    app: icinga2
  type: ClusterIP
