apiVersion: v1
kind: Service
metadata:
  name: icingaweb2
  namespace: monitoring
  labels:
    app: icinga2
spec:
  type: ClusterIP
  selector:
    app: icinga2
  ports:
    - name: http
      port: 80
      targetPort: 80
