
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-services
  namespace: {{ monitoring_ns }}
spec:
  namespaceSelector:
    matchNames:
      - {{ app_ns }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: petclinic
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
