autoDiscovery:
  clusterName: eks-obser-cluster

awsRegion: ap-southeast-1
sslCertPath: /etc/ssl/certs/ca-bundle.crt

extraArgs:
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  expander: least-waste
  scale-down-delay-after-add: 2m
  scan-interval: 10s
  max-node-provision-time: 5m

rbac:
  create: true

serviceMonitor:
  enabled: true
  interval: 15s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
